flowchart LR
  Open[Open] -->|NT| NTRespond>Respond to NT]
    NTRespond ---|"Sign off"| Spacer1{" "}
      Spacer1 --> NTDone[[NT Done]]
    NTRespond -->|"2NT"| NTInvitational([Rebid after NT invite])
      NTInvitational -->|Bid 3NT\nor Pass| NTDone
    NTRespond -->|"3 of a major (forcing)"| NTForcing([Rebid after NT->Suit force])
      NTForcing -->|Bid 3NT\nor 4 in the suit| NTDone

  Open -->|1 of a major| MajorRespond[Respond to Major opening]
    MajorRespond ---|Pass| Spacer4{" "}
      Spacer4 ---|"&nbsp;"| Done[[Suit Done]]

    MajorRespond -->|Same suit| SuitSupported>Rebid after support]
      SuitSupported ---|Pass or Game| Spacer2{" "}
        Spacer2 -->|"&nbsp;"| Done
      SuitSupported -->|"Invitation"| Invitational([Respond to invite])
        Invitational -->|Pass or Game| Done

    MajorRespond -->|"New suit (forcing)"| NewSuit[Rebid after new suit]
      NewSuit -->|All bids?| ResponderMultiple>Respond to multiple suits]
        ResponderMultiple -->|TBD| TBD[[TBD]]

    MajorRespond -->|NT| NTResponse>Rebid after NT]
      NTResponse ---|"Sign off"| Spacer3{" "}
        Spacer3 -->|"&nbsp;"| Done
      NTResponse -->|"Invitation"| Invitational
      NTResponse -->|Third suit| ResponderMultiple

  Open -->|1 of a minor| MinorRespond[Respond to Minor opening]
    MinorRespond ---|Pass| Spacer4
    MinorRespond -->|Same suit| SuitSupported
    MinorRespond -->|"New suit (forcing)"| NewSuit
    MinorRespond -->|NT| NTResponse

  Overcall[Overcall] -->|Suit| OvercallAdvance[Respond to suit Overcall]
    OvercallAdvance ---|Pass| SpacerOvercallPass{" "}
      SpacerOvercallPass -->|"&nbsp;"| OvercallDone[[Overcall Done]]
    OvercallAdvance -->|Support| OvercallRebid>Overcall Rebid]
      OvercallRebid -->|Any bid| OvercallDone
    OvercallAdvance -->|NT| OvercallRebid
    OvercallAdvance -->|New suit| OvercallRebid
    OvercallAdvance -->|Cue bid| Cue([Respond to Cue bid])
      Cue -->|Any bid| CueRebid>Cue Rebid]
        CueRebid -->|Any bid| OvercallDone

  Overcall -->|Double| TakeoutAdvance[Respond to Takeout Double]
    TakeoutAdvance -->|Pass| TakeoutRebid>Takeout Rebid]
      TakeoutRebid -->|Any bid| OvercallDone
    TakeoutAdvance -->|New suit| TakeoutRebid
    TakeoutAdvance -->|NT| TakeoutRebid
    TakeoutAdvance -->|Cue bid| Cue

  Overcall[Overcall] -->|NT| NTRespond

  Legend -->|Chosen bid| CaptainUndecided["Decision point\n(Captain undecided)"]
    CaptainUndecided -->|Chosen bid| Captain>Captain]
      Captain -->|Chosen bid| NotCaptain([Not Captain])
        NotCaptain -->|Chosen bid| LegendDone[[Done]]
      CaptainUndecided ---|Chosen bid| SpacerLegend1{" "}
        SpacerLegend1 ---|"(Spacers;\nignore them)"| SpacerLegend2{" "}
          SpacerLegend2 -->|"&nbsp;"| LegendDone

