flowchart LR
  Open[Open]
    Open -->|NT, standard| NTStandard>"Respond to NT\n(standard)"]
    Open -->|NT, conventions| NTConventions>"Respond to NT\n(conventions)"]

    NTStandard ---|"Sign off"| Spacer1{" "}
      Spacer1 --> NTDone[["NT Done"]]
    NTStandard -->|"2NT"| NTInvitational([Rebid after NT invite])
      NTInvitational -->|Bid 3NT\nor Pass| NTDone
    NTStandard -->|"3 of a major (forcing)"| NTForcing([Rebid after NT->Suit force])
      NTForcing -->|Bid 3NT\nor 4 in the suit| NTDone

    NTConventions -->|"2C (Stayman)"| Stayman([Required Stayman response])

  subgraph StaymanGraph [Stayman]
      Stayman -->|2D, 2S| StaymanNextBidSimple>Bid after Stayman]
        StaymanNextBidSimple -->|invitation| StaymanInviteRespond([Respond to invite])
      Stayman -->|2H| StaymanNextBidHearts>Bid after Stayman hearts bid]
        StaymanNextBidHearts -->|3H| StaymanInviteRespond
        StaymanNextBidHearts -->|2NT, 3NT| StaymanNoHeartFit([Bid after no heart fit])
  end
          StaymanInviteRespond -->|game| NTDone
          StaymanInviteRespond -->|pass| NTDone
        StaymanNextBidSimple -->|game| NTDone
        StaymanNextBidHearts -->|4H| NTDone
          StaymanNoHeartFit -->|Pass, 4S, 3NT| NTDone



    NTConventions -->|"2D or 2H\n(transfer to major)"| TransferResponse([Required transfer response])
    NTConventions -->|"2S\n(transfer to minor)"| TransferResponse

  subgraph Transfer [Transfers]
      TransferResponse -->|2 of major| TransferBid[Bid after major transfer]
        TransferBid -->|3 of the major| TransferInvite([Respond to invite])
        TransferBid -->|2NT| TransferSuitAndGameInvite[Respond to suit and game invite]

        TransferBid -->|3NT| TransferSwitchToMajor[Switch to the major]
        TransferBid -->|the other major| Tools[Use the tools, Luke]

      TransferResponse -->|3C| TransferMinor>Select the right minor]
  end
        TransferBid -->|pass, 4 of the major| NTDone
          TransferInvite -->|pass, 4 of the major| NTDone
          TransferSuitAndGameInvite -->|pass, 3NT, 3 of major, 4 of major| NTDone
          TransferSwitchToMajor -->|pass, 4 of the major| NTDone
          Tools --- NTDone
        TransferMinor -->|pass, 3D| NTDone


