flowchart LR
  Open[Open]
    Open -->|NT, regular| NTRespond>Respond to NT]
    Open -->|NT, conventions| NTConventions>Respond to NT]

  subgraph NTOpensGraph [non-stayman non-transfers]
    NTRespond ---|"Sign off"| Spacer1{" "}
      Spacer1 --> NTDoneRegular[["NT Done (regular)"]]
    NTRespond -->|"2NT"| NTInvitational([Rebid after NT invite])
      NTInvitational -->|Bid 3NT\nor Pass| NTDoneRegular
    NTRespond -->|"3 of a major (forcing)"| NTForcing([Rebid after NT->Suit force])
      NTForcing -->|Bid 3NT\nor 4 in the suit| NTDoneRegular
  end

    NTConventions -->|"2C (Stayman)"| Stayman([Responder has at least one 4 card major and 8+ points])
  subgraph StaymanGraph [Stayman]
      Stayman -->|2D| NoMajor([Opener has no 4 card major])
        NoMajor -->|2NT| NoFitInvitational([No suit fit, responder has <10 points])
          NoFitInvitational -->|Pass| InvitationalLowPoints([Opener has <17 points])
          NoFitInvitational  -->|3NT| InvitationalHighPoints([Opener has 17 points])
        NoMajor -->|3NT| NTGame([Responder has 10+ points])
      Stayman -->|2H| HeartMajor([Opener has 4 hearts, may have 4 spades])
        HeartMajor -->|2NT| SpadeSecondChance([Responder has 4 spades and <10 points])
          SpadeSecondChance -->|4S| SpadeChanceWon([Opener has 4 spades and 17 points])
          SpadeSecondChance -->|Pass| InvitationalLowPoints
        HeartMajor -->|3H| SuitInvitational([Suit fit, responder has <10 points])
          SuitInvitational -->|Pass| InvitationalLowPoints
          SuitInvitational -->|4 of suit| InvitationalHighPoints
        HeartMajor -->|4H| GameFitResponder([Suit fit, responder has 10+ points])
      Stayman -->|2S| SpadeMajor([Opener has 4 spades, does not have 4 hearts])
        SpadeMajor -->|2NT| NoFitInvitational
        SpadeMajor -->|3S| SuitInvitational
        SpadeMajor -->|4S| GameFitResponder
  end
            InvitationalLowPoints --- NTDone[["NT Done (conventions)"]]
            InvitationalHighPoints -->|Pass| NTDone
          NTGame -->|Pass| NTDone
            SpadeChanceWon -->|Pass| NTDone
          GameFitResponder -->|Pass| NTDone

    NTConventions -->|"2D or 2H (transfer to major)"| TransferMajor([Responder has a 5+ card major])
  subgraph MajorTransfer [Transfer to Major]
      TransferMajor -->|2 of major| AfterMajorTransfer([Accept the transfer])
        AfterMajorTransfer -->|Pass| LowPoints([Responder has 0-7 points])

        AfterMajorTransfer -->|2NT| FiveCardMajorLowPoints([Responder has exactly 5 cards and 8-9 points])
          FiveCardMajorLowPoints -->|Pass| TwoOfMajorLowPoints([Opener has only 2 of the major and <17 points])
          FiveCardMajorLowPoints -->|3NT| TwoOfMajorHighPoints([Opener has only 2 of the major and 17 points])
          FiveCardMajorLowPoints -->|3 of major| ThreeOfMajorLowPoints([Opener has 3+ of the major and <17 points])
          FiveCardMajorLowPoints -->|4 of major| FourOfMajorHighPoints([Opener has 3+ of the major and 17 points])


        AfterMajorTransfer -->|3NT| FiveCardMajorHighPoints([Responder has exactly 5 cards and 10+ points])
          FiveCardMajorHighPoints -->|Pass| OnlyTwo([Opener has 2 of the suit])
          FiveCardMajorHighPoints -->|4 of major| ThreeOrMore([Opener has 3 or more of the suit])

        AfterMajorTransfer -->|3 of major| SixCardMajorLowPoints([Responder has 6+ cards and 8-9 points])
          SixCardMajorLowPoints -->|Pass| LessThan17([Opener has less than 17 points])

        AfterMajorTransfer -->|4 of major| SixCardMajorHighPoints([Responder has 6+ cards and 10+ points])

  end
          LowPoints --- NTDone
            TwoOfMajorLowPoints --- NTDone
            TwoOfMajorHighPoints -->|Pass| NTDone
            ThreeOfMajorLowPoints -->|Pass| NTDone
            FourOfMajorHighPoints -->|Pass| NTDone
            OnlyTwo --- NTDone
            ThreeOrMore -->|Pass| NTDone
            LessThan17 --- NTDone
          SixCardMajorHighPoints -->|Pass| NTDone

  subgraph AdvancedTools [Advanced / Tools]
        AfterMajorTransfer -->|2S after transfer to 2H| HSTwoSuited([Responder is two suited with 5H and 4S and has 8+ points])
          HSTwoSuited -->|"Use the (NT) tools, Luke"| Tools([Bid according to other patterns])

        AfterMajorTransfer -->|3H after transfer to 2S| SHTwoSuited([Responder is two suited with 5S and 4H and has 10+ points])
          SHTwoSuited -->|"Use the (NT) tools, to game, Luke"| Tools

      TransferMajor -->|3 of major| SuperAcceptance([Super Acceptance - 17 points and 4 card support])
        SuperAcceptance -->|"Use the (NT) tools, Luke"| Tools
  end
            Tools --- NTDone


    NTConventions -->|"2S (transfer to minor)"| TransferMinor([Responder has 6+ of minor and a weak hand])
  subgraph MinorTransfer [Transfer to Minor]
      TransferMinor -->|3C| AfterMinorTransfer([Accept the transfer])
        AfterMinorTransfer -->|Pass| PreferClubs([Responder has clubs])
        AfterMinorTransfer -->|3D| PreferDiamonds([Responder has diamonds])
  end
          PreferClubs --- NTDone
          PreferDiamonds -->|Pass| NTDone



